# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:

  # - board: nice_nano_v2
  #   shield: ky113_dongle display_130_cat
  #   artifact-name: ky113_DongleWithCat
  
  # 一、【左、右、PAD三分体方案】
  - board: nice_nano_v2
    shield: ky113_left display_091_drum
    cmake-args: -DCONFIG_ZMK_DISPLAY=y
    artifact-name: ky113_M1_1_Left_central
  - board: nice_nano_v2
    shield: ky113_right
    artifact-name: ky113_M1_2_Right
  - board: nice_nano_v2
    shield: ky113_pad
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: ky113_M1_3_Pad


# # 二、【左、右分体方案】
#   - board: nice_nano_v2
#     shield: ky113_left  display_091_drum
#     cmake-args: -DCONFIG_ZMK_DISPLAY=y -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1
#     artifact-name: ky113_M2_1_Left_central
#   - board: nice_nano_v2
#     shield: ky113_right
#     artifact-name: ky113_M2_2_Right


# # 三、dongle+【左、右、PAD三分体方案】
#   - board: nice_nano_v2
#     shield: ky113_dongleh display_091_drumh
#     artifact-name: ky113_M3_1_DongleWithDrumH
#   - board: nice_nano_v2
#     shield: ky113_left
#     cmake-args: -DCONFIG_ZMK_DISPLAY=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
#     artifact-name: ky113_M3_2_Left_central
#   - board: nice_nano_v2
#     shield: ky113_right
#     artifact-name: ky113_M3_3_Right
#   - board: nice_nano_v2
#     shield: ky113_pad
#     cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
#     artifact-name: ky113_M3_4__Pad

# # 四、dongle+【左、右分体方案】
#   - board: nice_nano_v2
#     shield: ky113_dongleh display_091_drumh
#     cmake-args: -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
#     artifact-name: ky113_M4_1_DongleWithDrumH
#   - board: nice_nano_v2
#     shield: ky113_left
#     cmake-args: -DCONFIG_ZMK_DISPLAY=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
#     artifact-name: ky113_M4_2_Left_central
#   - board: nice_nano_v2
#     shield: ky113_right
#     artifact-name: ky113_M4_3_Right

# # 五、【PAD方案】
#   - board: nice_nano_v2
#     shield: ky113_pad
#     artifact-name: ky113_M5_Pad_central

# # 六、【重置固件方案】
#   - board: nice_nano_v2
#     shield: settings_reset
#     artifact-name: ky113_M6_settings_reset
